### ISSUE TITLE
发现两个bug：1. 标题中间的空格不是一个汉字符；2. 表格后的段落没有缩进

### ISSUE THREAD

**Issue by evibhm** [Rsweater/cug-thesis-typst#5]
来抓虫了，发现两个bug，template/thesis.typ ：
1. 标题中间的空格不是一个汉字符；
2. 表格后的段落没有缩进

**Comment by Rsweater** [comment]
感谢～ 
晚点查看修复～

> 来抓虫了，发现两个bug，template/thesis.typ ：
> 1. 标题中间的空格不是一个汉字符；
> 2. 表格后的段落没有缩进

**Comment by Rsweater** [comment]
@evibhm 朋友，你好~
已修复：
> 2. 表格后的段落没有缩进
朋友的提醒后发现列表、公式之类的后面也没有设置，目前公式仍然保留了没有缩进。因为公式后一般会跟注释“其中，`Backbone`是”之类的解释，这种咱们学校文档没有规定是否缩进，网上了解的似乎一般不缩进。朋友那边了解的是啥样？

未更改部分：
>1. 标题中间的空格不是一个汉字符；
这个目前采用的是一个英文字符，规范手册里面选中之后显示的是新罗马字体，所以想这个是不是英文字符？这个朋友那边了解的啥样？因为规范手册就写了个一个字符间距。所以，就按照个人理解来了。个人理解的是新罗马字体中不包含的CJK字体全部使用宋体（Windows、MacOS、思源宋体、Adobe宋体应该都可以），这个朋友咋理解的？

**Comment by evibhm** [comment]
@Rsweater 你好

对于**问题1**，[规范手册](https://github.com/marscfeng/cugThesis/blob/c439b0830b5607819750c6f1a730c4dd720425cf/%EF%BC%882015%EF%BC%89%E4%B8%AD%E5%9B%BD%E5%9C%B0%E8%B4%A8%E5%A4%A7%E5%AD%A6%EF%BC%88%E6%AD%A6%E6%B1%89%EF%BC%89%E7%A0%94%E7%A9%B6%E7%94%9F%E5%AD%A6%E4%BD%8D%E8%AE%BA%E6%96%87%E6%A0%BC%E5%BC%8F%E8%A7%84%E8%8C%83.pdf) 中提到序号与题名之间需要空一个汉字符，

![2024-12-28_16-32](https://github.com/user-attachments/assets/72d9e04a-f6cf-47d0-a17e-6a01dd11418c)

根据我的理解，应该是一个汉字的宽度即 `1em`。

对于**问题2**，公式之后确实没有规定是否需要缩进，按照我个人的理解，段首空两格这个样式应该是针对每一段文本的，只要起了新的段落，都应该有空两格这个缩进的行为。而Typst的规则似乎不认为在标题、`figure` 等这些内容后是一个新的段落（这点应该与 $\LaTeX$ 类似）。可能相关的[参考资料](https://evian-zhang.github.io/articles/LaTeX/LaTeX%E5%85%A5%E9%97%A8(%E5%85%AD)/56171762.html#:~:text=%E7%94%B1%E4%BA%8E%E8%8B%B1%E6%96%87%E8%AE%BA%E6%96%87%E7%9A%84%E5%86%99%E4%BD%9C%E8%A7%84%E8%8C%83%EF%BC%8C%E6%AF%8F%E4%B8%AA%E7%AB%A0%E8%8A%82%E7%9A%84%E9%A6%96%E6%AE%B5%E6%98%AF%E4%B8%8D%E7%BC%A9%E8%BF%9B%E7%9A%84%E3%80%82)

在规范手册的示例中，公式后的段落进行了缩进：

![2024-12-28_16-37](https://github.com/user-attachments/assets/79d0fa93-a27a-49e4-99ba-ebc51aa0d311)

这个问题**也许**可以通过下面的方式解决：

```typst
show block: it => {
  it
  fake-par
}
```

对于不想进行缩进的场景，可以

```typst
#let noindent = h(-2em)
```

**Comment by Rsweater** [comment]
@evibhm 
感谢~ 问题确实存在。之前参考的《写作规范》有问题，还以为各个学院的不一样，重新下载了发现：可能是自己不小心改掉了。
已更新~~
请最新关注[Commits](https://github.com/Rsweater/cug-thesis-typst/commits/main/)~~ 
欢迎再来~

**Comment by Rsweater** [comment]
校友提到的问题已解决~~ 
所以，计划暂时关闭这个Issue，如果还有其他问题可重开或者新开~
